name: motion_toast
description: 'A beautiful designed toast with animations, contains multiple built in designs and let you design your toast'
version: 2.10.0
homepage: 'https://github.com/koukibadr/Motion-Toast'
funding:
- 'https://www.buymeacoffee.com/koukibadr'
screenshots:
- description: Motion Toast pacakge front image.
  path: example/warning_mt.png
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
